<x-layouts.admin title="Range Locations | Forest Inventory" heading="Range Locations" subheading="Set the rounds, beats, places, hectares, and years available to each range">
    <div class="grid gap-5 xl:grid-cols-[.8fr_1.2fr]">
        <form class="rounded-lg border border-emerald-100 bg-white p-5 shadow-sm" method="POST" action="{{ route('range-locations.store') }}">
            @csrf
            <h2 class="text-base font-semibold text-slate-950">Add location</h2>
            <div class="mt-5 space-y-4">
                <div><label class="form-label" for="range_id">Range</label><select id="range_id" class="form-select" name="range_id" required><option value="" disabled @selected(!old('range_id'))>Choose range...</option>@foreach($ranges as $range)<option value="{{ $range->id }}" @selected(old('range_id') == $range->id)>{{ $range->name }}</option>@endforeach</select>@error('range_id')<p class="form-error">{{ $message }}</p>@enderror</div>
                <div><label class="form-label" for="round">Round</label><input id="round" class="form-input" name="round" value="{{ old('round') }}" required>@error('round')<p class="form-error">{{ $message }}</p>@enderror</div>
                <div><label class="form-label" for="beat">Beat</label><input id="beat" class="form-input" name="beat" value="{{ old('beat') }}" required></div>
                <div><label class="form-label" for="place">Place</label><input id="place" class="form-input" name="place" value="{{ old('place') }}" required></div>
                <div class="grid gap-4 sm:grid-cols-2"><div><label class="form-label" for="hectares">Ha.</label><input id="hectares" class="form-input" name="hectares" value="{{ old('hectares') }}" type="number" min="0" step="0.01"></div><div><label class="form-label" for="place_year">Place Year</label><select id="place_year" class="form-select" name="place_year"><option value="">Choose...</option>@foreach($placeYears as $placeYear)<option value="{{ $placeYear }}" @selected(old('place_year') === $placeYear)>{{ $placeYear }}</option>@endforeach</select></div></div>
            </div>
            <button class="primary-button mt-5 w-full" type="submit">Add location</button>
        </form>
        <div class="rounded-lg border border-emerald-100 bg-white shadow-sm"><div class="border-b border-emerald-100 px-5 py-4"><h2 class="font-semibold text-slate-950">Configured locations</h2><p class="text-sm text-slate-500">Only the matching range can use its rounds.</p></div><div class="overflow-x-auto"><table class="data-table"><thead><tr><th>Range</th><th>Round</th><th>Beat</th><th>Place</th><th>Ha.</th><th>Year</th><th class="text-right">Action</th></tr></thead><tbody>@forelse($locations as $location)<tr><td>{{ $location->range->name }}</td><td>{{ $location->round }}</td><td>{{ $location->beat }}</td><td>{{ $location->place }}</td><td>{{ $location->hectares ?? '-' }}</td><td>{{ $location->place_year ?? '-' }}</td><td><div class="flex justify-end gap-2"><details><summary class="secondary-button cursor-pointer list-none">Edit</summary><form class="mt-2 grid w-80 gap-2 rounded-lg border border-emerald-100 bg-white p-3 shadow-lg" method="POST" action="{{ route('range-locations.update', $location) }}">@csrf @method('PUT')<select class="form-select" name="range_id" required>@foreach($ranges as $range)<option value="{{ $range->id }}" @selected($location->range_id === $range->id)>{{ $range->name }}</option>@endforeach</select><input class="form-input" name="round" value="{{ $location->round }}" required><input class="form-input" name="beat" value="{{ $location->beat }}" required><input class="form-input" name="place" value="{{ $location->place }}" required><div class="grid grid-cols-2 gap-2"><input class="form-input" name="hectares" type="number" min="0" step="0.01" value="{{ $location->hectares }}"><select class="form-select" name="place_year"><option value="">Choose...</option>@foreach($placeYears as $placeYear)<option value="{{ $placeYear }}" @selected($location->place_year === $placeYear)>{{ $placeYear }}</option>@endforeach</select></div><button class="primary-button" type="submit">Save changes</button></form></details><form method="POST" action="{{ route('range-locations.destroy', $location) }}" onsubmit="return confirm('Remove this location?');">@csrf @method('DELETE')<button class="secondary-button text-red-700" type="submit">Delete</button></form></div></td></tr>@empty<tr><td colspan="7" class="text-center text-slate-500">No locations configured.</td></tr>@endforelse</tbody></table></div>@if($locations->hasPages())<div class="border-t border-emerald-100 px-5 py-4">{{ $locations->links() }}</div>@endif</div>
    </div>
</x-layouts.admin>
