<x-layouts.admin title="Allotment to Range | Forest Inventory" heading="Allotment to Range" subheading="Distribute division allotments across ranges">
    <form class="space-y-5" method="POST" action="{{ route('division.allotments-to-range.store') }}" data-allotment-to-range-form data-details-url="{{ url('division/allotment-to-range/budget-details') }}">
        @csrf
        @if(session('status'))<div class="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800">{{ session('status') }}</div>@endif
        <section class="rounded-lg border border-emerald-100 bg-white shadow-sm"><div class="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-6">
            <div><label class="form-label" for="budget_code_id">Budget Code</label><select id="budget_code_id" class="form-select" name="budget_code_id" required data-range-budget-code><option value="" selected disabled>Choose...</option>@foreach($budgetCodes as $budgetCode)<option value="{{ $budgetCode->id }}">{{ $budgetCode->budget_code }}</option>@endforeach</select></div>
            <div><label class="form-label">Rate</label><input class="form-input bg-slate-50" readonly data-budget-rate></div><div><label class="form-label">Target</label><input class="form-input bg-slate-50" readonly data-budget-target></div>
            <div><label class="form-label">Allotment from Circle</label><input class="form-input bg-slate-50" readonly data-budget-allotment></div><div><label class="form-label">Adjusted Allotment</label><input class="form-input bg-slate-50" readonly data-budget-adjusted></div>
            <div><label class="form-label" for="distribution_percent">Distribute as per %</label><div class="flex"><input id="distribution_percent" class="form-input rounded-r-none" type="number" min="0" max="100" step="0.01" data-distribution-percent><button class="secondary-button rounded-l-none" type="button" data-distribute-percent>Distribute</button></div></div>
            <div class="xl:col-span-2"><label class="form-label">Pending Target</label><input class="form-input bg-slate-50" readonly data-budget-pending-target></div><div class="xl:col-span-2"><label class="form-label">Scheme</label><input class="form-input bg-slate-50" readonly data-budget-scheme></div><div class="xl:col-span-2"><label class="form-label">Model</label><input class="form-input bg-slate-50" readonly data-budget-model></div>
            <div class="md:col-span-2 xl:col-span-6"><label class="form-label" for="remark">Remark</label><textarea id="remark" class="form-textarea" name="remark" rows="2"></textarea></div>
        </div></section>
        <section class="overflow-x-auto rounded-lg border border-emerald-100 bg-white shadow-sm"><table class="data-table compact-data-table min-w-[100rem]"><thead><tr><th>Range</th><th>Existing Target</th><th>Existing Allotment</th><th>Expenditure</th><th>Vouchers Entered</th><th>Remaining Allotment</th><th>Target (+-)</th><th>Allotment (+-)</th><th>New Target</th><th>New Allotment</th></tr></thead><tbody data-range-allocation-rows><tr><td colspan="10" class="text-center">Select a budget code to load its allotment details.</td></tr></tbody></table></section>
        <section class="rounded-lg border border-emerald-100 bg-white shadow-sm"><div class="flex justify-end gap-3 p-5"><button class="primary-button" type="submit">Save Distribution</button></div></section>
    </form>
</x-layouts.admin>
