@php
    $isEdit = filled($beneficiary) && !$isCopy;
    $action = $isEdit ? route('finance.registration.wl-beneficiaries.update', $beneficiary) : route('finance.registration.wl-beneficiaries.store');
    $field = fn (string $name, mixed $default = '') => old($name, $beneficiary?->{$name} ?? $default);
    $beats = collect($rounds)->flatten()->unique()->sort()->values();
@endphp
<x-layouts.admin title="WL Beneficiary Registration | Forest Inventory" heading="WL Beneficiary Registration" subheading="Register wildlife beneficiary details">
    <form class="space-y-5" method="POST" action="{{ $action }}" enctype="multipart/form-data" data-wl-beneficiary-form @if($isCopy) data-wl-copy-mode @endif>
        @csrf @if($isEdit) @method('PUT') @endif
        @unless($isEdit)
            <section class="rounded-lg border border-emerald-100 bg-white shadow-sm"><div class="border-b border-emerald-100 px-5 py-4"><h2 class="text-base font-semibold text-slate-950">Copy or start new entry</h2><p class="mt-1 text-sm text-slate-500">Enter Sr. No. to copy and click Copy Entry, or do a totally new entry.</p></div><div class="grid gap-4 p-5 lg:grid-cols-[1fr_1fr_auto]"><div><label class="form-label" for="copy">Sr. No. to copy</label><input id="copy" class="form-input" name="copy" value="{{ request('copy') }}" placeholder="Enter existing Sr. No."></div><div class="flex items-end gap-3"><button class="secondary-button" type="submit" formmethod="GET" formnovalidate formaction="{{ route('finance.registration.wl-beneficiaries.create') }}">Copy Entry</button><div><label class="form-label" for="wl_edit_copied_entry">Edit copied entry?</label><label class="toggle-field"><input id="wl_edit_copied_entry" type="checkbox" data-wl-edit-copied-entry><span></span><strong>Enable editing after copy</strong></label></div></div></div>@if(request('copy') && !$isCopy)<p class="px-5 pb-5 form-error">No beneficiary found with this Sr. No.</p>@endif</section>
        @endunless
        <section class="rounded-lg border border-emerald-100 bg-white shadow-sm"><div class="border-b border-emerald-100 px-5 py-4"><h2 class="text-base font-semibold text-slate-950">Beneficiary details</h2></div><div class="grid gap-4 p-5 md:grid-cols-2 xl:grid-cols-4">
            <div><label class="form-label">Sr. No. (of this Beneficiary)</label><input class="form-input" value="{{ $isEdit ? $beneficiary->serial_number : $nextSerial }}" readonly></div>
            <div><label class="form-label" for="wl_bene_code">WL Bene. Code</label><input id="wl_bene_code" class="form-input" name="wl_bene_code" value="{{ $field('wl_bene_code') }}" required></div>
            <div><label class="form-label" for="round">Round</label><select id="round" class="form-select" name="round" required><option value="" disabled @selected(blank($field('round'))) >Choose...</option>@foreach(array_keys($rounds) as $round)<option value="{{ $round }}" @selected($field('round') === $round)>{{ $round }}</option>@endforeach</select></div>
            <div><label class="form-label" for="beat">Beat</label><select id="beat" class="form-select" name="beat" required><option value="" disabled @selected(blank($field('beat'))) >Choose...</option>@foreach($beats as $beat)<option value="{{ $beat }}" @selected($field('beat') === $beat)>{{ $beat }}</option>@endforeach</select></div>
            <div><label class="form-label" for="yojana_name">Name of Yojana</label><select id="yojana_name" class="form-select" name="yojana_name" required><option value="" disabled @selected(blank($field('yojana_name'))) >Choose...</option>@foreach(['Killing by Wild Animal', 'Open Well', 'Machan'] as $yojana)<option value="{{ $yojana }}" @selected($field('yojana_name') === $yojana)>{{ $yojana }}</option>@endforeach</select></div>
            <div><label class="form-label" for="full_name">Beneficiary Full Name</label><input id="full_name" class="form-input" name="full_name" value="{{ $field('full_name') }}" required></div><div><label class="form-label" for="name_gujarati">Bene. Name In Gujarati</label><input id="name_gujarati" class="form-input" name="name_gujarati" value="{{ $field('name_gujarati') }}"></div><div><label class="form-label" for="mobile_no">Mobile No.</label><input id="mobile_no" class="form-input" name="mobile_no" value="{{ $field('mobile_no') }}"></div>
            <div><label class="form-label" for="gender">Gender</label><select id="gender" class="form-select" name="gender"><option value="">Choose...</option>@foreach(['Male', 'Female'] as $gender)<option value="{{ $gender }}" @selected($field('gender') === $gender)>{{ $gender }}</option>@endforeach</select></div><div><label class="form-label" for="category">Category</label><select id="category" class="form-select" name="category"><option value="">Choose...</option>@foreach(['Open', 'SEBC', 'SC', 'ST'] as $category)<option value="{{ $category }}" @selected($field('category') === $category)>{{ $category }}</option>@endforeach</select></div>
            <div class="md:col-span-2"><label class="form-label" for="address">Address of Beni.</label><input id="address" class="form-input" name="address" value="{{ $field('address') }}"></div><div><label class="form-label" for="pin_code">Pin Code of Beni.</label><input id="pin_code" class="form-input" name="pin_code" value="{{ $field('pin_code') }}"></div>
            <div><label class="form-label" for="taluka">Taluka</label><select id="taluka" class="form-select" name="taluka"><option value="">Choose...</option>@foreach(['Himmatnagar','Idar','Vadali','Khedbrahma','Vijaynagar','Prantij','Talod','Poshina','Modasa','Meghraj','Malpur','Bayad','Dhansura','Bhiloda'] as $taluka)<option value="{{ $taluka }}" @selected($field('taluka') === $taluka)>{{ $taluka }}</option>@endforeach</select></div><div><label class="form-label" for="district">District</label><input id="district" class="form-input" name="district" value="{{ $field('district') }}"></div><div><label class="form-label" for="village">Village</label><input id="village" class="form-input" name="village" value="{{ $field('village') }}"></div><div><label class="form-label" for="survey_block_no">Survey No. / Block No.</label><input id="survey_block_no" class="form-input" name="survey_block_no" value="{{ $field('survey_block_no') }}"></div>
            <div><label class="form-label" for="id_type">ID Type</label><select id="id_type" class="form-select" name="id_type"><option value="">Choose...</option>@foreach(['Aadhar Card','Pan Card','Voter ID','Licence'] as $idType)<option value="{{ $idType }}" @selected($field('id_type') === $idType)>{{ $idType }}</option>@endforeach</select></div><div><label class="form-label" for="id_no">ID No.</label><input id="id_no" class="form-input" name="id_no" value="{{ $field('id_no') }}"></div><div><label class="form-label" for="gps_n">GPS-N</label><input id="gps_n" class="form-input" name="gps_n" value="{{ $field('gps_n') }}"></div><div><label class="form-label" for="gps_e">GPS-E</label><input id="gps_e" class="form-input" name="gps_e" value="{{ $field('gps_e') }}"></div>
            <div><label class="form-label" for="gps">GPS</label><input id="gps" class="form-input" name="gps" value="{{ $field('gps') }}"></div><div><label class="form-label" for="selection_year">Bene. Selection Year</label><select id="selection_year" class="form-select" name="selection_year"><option value="">Choose...</option>@foreach($selectionYears as $year)<option value="{{ $year }}" @selected($field('selection_year') === $year)>{{ $year }}</option>@endforeach</select></div><div class="md:col-span-2"><label class="form-label" for="link_of_doc">Link of Doc</label><input id="link_of_doc" class="form-input" name="link_of_doc" type="url" value="{{ $field('link_of_doc') }}" placeholder="https://..."></div><div class="md:col-span-2 xl:col-span-4"><label class="form-label" for="remark">Remark for WL Beneficiary</label><textarea id="remark" class="form-textarea" name="remark" rows="3">{{ $field('remark') }}</textarea></div><div class="md:col-span-2"><label class="form-label" for="attachments">Upload files</label><input id="attachments" class="form-input" name="attachments[]" type="file" multiple><p class="mt-1 text-xs text-slate-500">Any file type, up to 20 MB each.</p>@foreach($beneficiary?->attachments ?? [] as $attachment)<a class="mr-3 mt-1 inline-block text-xs font-semibold text-emerald-700" target="_blank" href="{{ Storage::disk('public')->url($attachment) }}">View uploaded file</a>@endforeach @error('attachments.*')<p class="form-error">{{ $message }}</p>@enderror</div>
        </div></section>
        <section class="rounded-lg border border-emerald-100 bg-white shadow-sm"><div class="flex flex-col gap-4 p-5 md:flex-row md:items-center md:justify-between"><div><label class="form-label">Party Status</label><p class="text-sm text-slate-500">Deactivate this beneficiary to stop future payments.</p><div class="mt-3 flex gap-3"><label class="radio-pill"><input type="radio" name="party_status" value="Active" @checked($field('party_status', 'Active') === 'Active')><span>Active</span></label><label class="radio-pill"><input type="radio" name="party_status" value="Deactive" @checked($field('party_status', 'Active') === 'Deactive')><span>Deactive</span></label></div></div><div class="flex gap-3"><a class="secondary-button" href="{{ route('finance.registration.wl-beneficiaries.index') }}">View Details</a><button class="primary-button" type="submit">{{ $isEdit ? 'Update' : 'Submit' }}</button></div></div></section>
    </form>
</x-layouts.admin>