<x-layouts.admin title="WL Beneficiary Details | Forest Inventory" heading="WL Beneficiary Details" subheading="All registered wildlife beneficiary fields for this range">
    <div class="space-y-5"><div class="flex items-center justify-between"><div><h2 class="text-base font-semibold text-slate-950">Registered beneficiaries</h2><p class="mt-1 text-sm text-slate-500">Scroll horizontally to review every saved field.</p></div><div class="flex w-full items-center gap-3 sm:w-auto"><div class="w-full sm:w-80"><label class="sr-only" for="wlBeneficiarySearch">Search beneficiaries</label><input id="wlBeneficiarySearch" class="form-input min-h-9 py-1.5" type="search" placeholder="Search any beneficiary detail..." data-wl-beneficiary-search></div><a class="primary-button whitespace-nowrap" href="{{ route('finance.registration.wl-beneficiaries.create') }}">Add Beneficiary</a></div></div>
    <div class="rounded-lg border border-emerald-100 bg-white shadow-sm"><div class="overflow-x-auto"><table class="data-table compact-data-table min-w-[160rem]"><thead><tr><th>Sr.</th><th>WL Bene. Code</th><th>Full Name</th><th>Name Gujarati</th><th>Round</th><th>Beat</th><th>Yojana</th><th>Mobile</th><th>Gender</th><th>Address</th><th>PIN</th><th>Category</th><th>Taluka</th><th>District</th><th>Village</th><th>Survey / Block No.</th><th>ID Type</th><th>ID No.</th><th>GPS-N</th><th>GPS-E</th><th>GPS</th><th>Selection Year</th><th>Remark</th><th>Document Link</th><th>Files</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>
    @forelse($beneficiaries as $beneficiary)
        <tr data-wl-beneficiary-row><td>{{ $beneficiary->serial_number }}</td><td>{{ $beneficiary->wl_bene_code }}</td><td>{{ $beneficiary->full_name }}</td><td>{{ $beneficiary->name_gujarati ?? '-' }}</td><td>{{ $beneficiary->round }}</td><td>{{ $beneficiary->beat }}</td><td>{{ $beneficiary->yojana_name }}</td><td>{{ $beneficiary->mobile_no ?? '-' }}</td><td>{{ $beneficiary->gender ?? '-' }}</td><td class="max-w-xs"><span class="block truncate" title="{{ $beneficiary->address }}">{{ $beneficiary->address ?? '-' }}</span></td><td>{{ $beneficiary->pin_code ?? '-' }}</td><td>{{ $beneficiary->category ?? '-' }}</td><td>{{ $beneficiary->taluka ?? '-' }}</td><td>{{ $beneficiary->district ?? '-' }}</td><td>{{ $beneficiary->village ?? '-' }}</td><td>{{ $beneficiary->survey_block_no ?? '-' }}</td><td>{{ $beneficiary->id_type ?? '-' }}</td><td>{{ $beneficiary->id_no ?? '-' }}</td><td>{{ $beneficiary->gps_n ?? '-' }}</td><td>{{ $beneficiary->gps_e ?? '-' }}</td><td>{{ $beneficiary->gps ?? '-' }}</td><td>{{ $beneficiary->selection_year ?? '-' }}</td><td class="max-w-xs"><span class="block truncate" title="{{ $beneficiary->remark }}">{{ $beneficiary->remark ?? '-' }}</span></td><td>@if($beneficiary->link_of_doc)<a class="font-semibold text-emerald-700" target="_blank" href="{{ $beneficiary->link_of_doc }}">Open link</a>@else - @endif</td><td>@forelse($beneficiary->attachments ?? [] as $attachment)<a class="mr-2 font-semibold text-emerald-700" target="_blank" href="{{ Storage::disk('public')->url($attachment) }}">View file</a>@empty - @endforelse</td><td><span class="inline-flex rounded-full px-2 py-0.5 text-xs font-bold {{ $beneficiary->party_status === 'Active' ? 'bg-emerald-50 text-emerald-700' : 'bg-red-50 text-red-700' }}">{{ $beneficiary->party_status }}</span></td><td>{{ $beneficiary->created_at->format('d M Y') }}</td><td><div class="flex flex-nowrap gap-1 whitespace-nowrap"><a class="secondary-button min-h-7 px-1.5 py-0.5 text-[10px]" href="{{ route('finance.registration.wl-beneficiaries.edit', $beneficiary) }}">Edit</a><form method="POST" action="{{ route('finance.registration.wl-beneficiaries.status', $beneficiary) }}">@csrf @method('PATCH')<button class="secondary-button min-h-7 px-1.5 py-0.5 text-[10px]">{{ $beneficiary->party_status === 'Active' ? 'Deactivate' : 'Activate' }}</button></form><form method="POST" action="{{ route('finance.registration.wl-beneficiaries.destroy', $beneficiary) }}" onsubmit="return confirm('Delete this beneficiary?');">@csrf @method('DELETE')<button class="secondary-button min-h-7 border-red-200 bg-red-50 px-1.5 py-0.5 text-[10px] text-red-700">Delete</button></form></div></td></tr>
    @empty
        <tr><td colspan="28" class="text-center text-slate-500">No WL beneficiaries available.</td></tr>
    @endforelse
    </tbody></table></div>@if($beneficiaries->hasPages())<div class="border-t border-emerald-100 px-5 py-4">{{ $beneficiaries->links() }}</div>@endif</div></div>
</x-layouts.admin>