<?php
namespace App\Http\Controllers\Admin\Finance;
use App\Http\Controllers\Controller;use App\Models\{AllotmentAdjustment,AllotmentFromCircle,AllotmentToRange,BudgetCode};use Illuminate\Http\{JsonResponse,RedirectResponse,Request};use Illuminate\Support\Facades\DB;use Illuminate\Validation\Rule;use Illuminate\View\View;
class AllotmentAdjustmentController extends Controller {
 public function index(Request $r):View{$this->auth($r);return view('admin.finance.allotment-adjustments.index',['entries'=>AllotmentAdjustment::where('division_id',$r->user()->id)->latest()->paginate(10)]);}
 public function create(Request $r):View{$this->auth($r);return view('admin.finance.allotment-adjustments.form',['adjustment'=>null,'budgetCodes'=>BudgetCode::orderBy('budget_code')->get()]);}
 public function edit(Request $r,AllotmentAdjustment $a):View{$this->owner($r,$a);return view('admin.finance.allotment-adjustments.form',['adjustment'=>$a,'budgetCodes'=>BudgetCode::orderBy('budget_code')->get()]);}
 public function details(Request $r,BudgetCode $budgetCode):JsonResponse{$this->auth($r);return response()->json($this->detailsFor($r,$budgetCode,$r->integer('exclude')));}
 public function store(Request $r):RedirectResponse{$this->auth($r);$d=$this->valid($r);$this->available($r,$d);AllotmentAdjustment::create($this->payload($r,$d));return redirect()->route('division.allotment-adjustments.index')->with('status','Allotment adjustment saved successfully.');}
 public function update(Request $r,AllotmentAdjustment $a):RedirectResponse{$this->owner($r,$a);$d=$this->valid($r);$this->available($r,$d,$a->id);$a->update($this->payload($r,$d,$a->id));return redirect()->route('division.allotment-adjustments.index')->with('status','Allotment adjustment updated successfully.');}
 public function destroy(Request $r,AllotmentAdjustment $a):RedirectResponse{$this->owner($r,$a);$a->delete();return back()->with('status','Allotment adjustment deleted successfully.');}
 private function valid(Request $r):array{return $r->validate(['from_budget_code_id'=>['required','integer',Rule::exists('budget_codes','id')],'to_budget_code_id'=>['required','integer','different:from_budget_code_id',Rule::exists('budget_codes','id')],'amount'=>['required','numeric','gt:0'],'remark'=>['nullable','string','max:1000']]);}
 private function payload(Request $r,array $d,?int $exclude=null):array{return array_merge($d,['division_id'=>$r->user()->id,'data'=>['from'=>$this->detailsFor($r,BudgetCode::findOrFail($d['from_budget_code_id']),$exclude),'to'=>$this->detailsFor($r,BudgetCode::findOrFail($d['to_budget_code_id']),$exclude)]]);}
 private function available(Request $r,array $d,?int $exclude=null):void{abort_if((float)$d['amount']>(float)$this->detailsFor($r,BudgetCode::findOrFail($d['from_budget_code_id']),$exclude)['pending_allotment'],422,'Transfer amount must be smaller than or equal to the pending allotment.');}
 private function detailsFor(Request $r,BudgetCode $b,?int $exclude=null):array{$circle=AllotmentFromCircle::where('division_id',$r->user()->id)->where('budget_code_id',$b->id)->latest()->first();abort_unless($circle,404,'No allotment from Circle is available for this budget code.');$q=AllotmentAdjustment::where('division_id',$r->user()->id)->when($exclude,fn($q)=>$q->whereKeyNot($exclude));$out=(float)(clone $q)->where('from_budget_code_id',$b->id)->sum('amount');$in=(float)(clone $q)->where('to_budget_code_id',$b->id)->sum('amount');$distributed=(float)AllotmentToRange::where('division_id',$r->user()->id)->where('budget_code_id',$b->id)->sum(DB::raw("CAST(JSON_UNQUOTE(JSON_EXTRACT(data, '$.allotment')) AS DECIMAL(15,2))"));$circleAmount=(float)($circle->data['allotment']??0);$adjusted=$circleAmount+$in-$out;return ['id'=>$b->id,'budget_code'=>$b->budget_code,'scheme'=>$b->scheme,'class'=>$b->object_class,'model'=>$b->model,'allotment_from_circle'=>$circleAmount,'adjusted_allotment'=>$adjusted,'pending_allotment'=>$adjusted-$distributed];}
 private function auth(Request $r):void{abort_unless($r->user()->isDivision(),403);} private function owner(Request $r,AllotmentAdjustment $a):void{$this->auth($r);abort_unless($a->division_id===$r->user()->id,403);}
}
