<?php
namespace App\Http\Controllers\Admin\Finance;
use App\Http\Controllers\Controller; use App\Models\RangeLocation; use App\Models\SfBeneficiary; use Illuminate\Http\RedirectResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\Storage; use Illuminate\Validation\Rule; use Illuminate\View\View;
class SfBeneficiaryController extends Controller {
 public function index(Request $r): View { $this->auth($r); return view('admin.finance.registration.sf-beneficiaries.index',['beneficiaries'=>SfBeneficiary::where('range_id',$r->user()->id)->latest('serial_number')->paginate(10)]); }
 public function create(Request $r): View { $this->auth($r); $copy=$r->filled('copy')?SfBeneficiary::where('range_id',$r->user()->id)->where('serial_number',$r->integer('copy'))->first():null; return $this->form($r,$copy,(bool)$copy); }
 public function store(Request $r): RedirectResponse { $this->auth($r); $data=$this->files($r,$this->validated($r)); $data['range_id']=$r->user()->id; $data['serial_number']=$this->next($r); SfBeneficiary::create($data); return redirect()->route('finance.registration.sf-beneficiaries.index')->with('status','Your data is submitted.'); }
 public function edit(Request $r,SfBeneficiary $beneficiary): View { $this->own($r,$beneficiary); return $this->form($r,$beneficiary,false); }
 public function update(Request $r,SfBeneficiary $beneficiary): RedirectResponse { $this->own($r,$beneficiary); $beneficiary->update($this->files($r,$this->validated($r),$beneficiary)); return redirect()->route('finance.registration.sf-beneficiaries.index')->with('status','SF beneficiary updated successfully.'); }
 public function toggleStatus(Request $r,SfBeneficiary $beneficiary): RedirectResponse { $this->own($r,$beneficiary); $beneficiary->update(['party_status'=>$beneficiary->party_status==='Active'?'Deactive':'Active']); return back()->with('status','Beneficiary status updated successfully.'); }
 public function destroy(Request $r,SfBeneficiary $beneficiary): RedirectResponse { $this->own($r,$beneficiary); Storage::disk('public')->delete($beneficiary->attachments??[]); $beneficiary->delete(); return back()->with('status','SF beneficiary deleted successfully.'); }
 private function form(Request $r,?SfBeneficiary $b,bool $copy): View { return view('admin.finance.registration.sf-beneficiaries.form',['beneficiary'=>$b,'isCopy'=>$copy,'nextSerial'=>$b&&!$copy?$b->serial_number:$this->next($r),'rounds'=>$this->rounds($r),'years'=>$this->years(),'banks'=>$this->banks(),'yojanas'=>$this->yojanas()]); }
 private function validated(Request $r): array { return $r->validate(['sf_bene_code'=>['required','string'],'round'=>['required',Rule::in(array_keys($this->rounds($r)))],'beat'=>['required','string'],'yojana_name'=>['required',Rule::in($this->yojanas())],'full_name'=>['required','string'],'name_gujarati'=>['nullable','string'],'mobile_no'=>['nullable','string'],'gender'=>['nullable',Rule::in(['Male','Female'])],'father_name'=>['nullable','string'],'birth_date'=>['nullable','date'],'address'=>['nullable','string'],'pin_code'=>['nullable','string'],'bank_name'=>['nullable','string'],'account_no'=>['nullable','string'],'ifsc'=>['nullable','string'],'branch'=>['nullable','string'],'category'=>['nullable',Rule::in(['Open','SEBC','SC','ST'])],'taluka'=>['nullable','string'],'district'=>['nullable','string'],'village'=>['nullable','string'],'survey_block_no'=>['nullable','string'],'id_type'=>['nullable',Rule::in(['Aadhar Card','Pan Card','Voter ID','Licence'])],'id_no'=>['nullable','string'],'gps_n'=>['nullable','string'],'gps_e'=>['nullable','string'],'gps'=>['nullable','string'],'selection_year'=>['nullable',Rule::in($this->years())],'hactor_dcp_plants'=>['nullable','string'],'link_of_doc'=>['nullable','url'],'attachments'=>['nullable','array'],'attachments.*'=>['file','max:20480'],'party_status'=>['required',Rule::in(['Active','Deactive'])]]); } private function files(Request $r,array $data,?SfBeneficiary $b=null): array { if(!$r->hasFile('attachments')){unset($data['attachments']);return $data;} $data['attachments']=array_merge($b?->attachments??[],collect($r->file('attachments'))->map(fn($f)=>$f->store('sf-beneficiary-attachments','public'))->all()); return $data; }
 private function rounds(Request $r): array{return RangeLocation::where('range_id',$r->user()->id)->get()->groupBy('round')->map(fn($l)=>$l->pluck('beat')->unique()->values()->all())->all();} private function years(): array{$y=(int)now()->format('Y');$s=(int)now()->format('n')<4?$y-1:$y;return collect(range($s-30,$s+30))->map(fn($v)=>sprintf('%d-%02d',$v,($v+1)%100))->sortDesc()->values()->all();} private function yojanas():array{return ['DCP Nursery- SCP (SHG)','Agro Forestry Yojana','Agro Forestry Yojana (SCP)','Agro Forestry Yojana (Trible)','DCP Nursery','DCP Nursery (SCP)','DCP Nursery (Trible)','RDFL','RDFL (SCP)','RDFL (Trible)','VruxKheti','VruxKheti (SCP)','VruxKheti (Trible)','National Bamboo Mission','National Bamboo Mission (SCP)','National Bamboo Mission (Trible)'];} private function banks():array{return ['State Bank of India','Bank of Baroda','Punjab National Bank','Saurashtra Gramin Bank','Axis Bank','Bank of India','Canara Bank','HDFC Bank','ICICI Bank','IDBI Bank','Indian Bank','Kotak Mahindra Bank','Union Bank of India','Central Bank of India','Yes Bank','IndusInd Bank','Federal Bank Limited','Bandhan Bank','RBL Bank','UCO Bank'];} private function next(Request $r):int{return ((int)SfBeneficiary::where('range_id',$r->user()->id)->max('serial_number'))+1;} private function auth(Request $r):void{abort_unless($r->user()->isRange(),403);} private function own(Request $r,SfBeneficiary $b):void{abort_unless($r->user()->isRange()&&$b->range_id===$r->user()->id,403);} }